### ISSUE TITLE
Support for standalone binary (musl)

### ISSUE THREAD

**Issue by danielhstahl** [adwhit/rust-nlopt#2]
I'm having trouble building a project with nlopt with a musl target.

A minimum docker container demonstrating this:
`
FROM` ekidd/rust-musl-builder:nightly-2020-11-19 AS build
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo install --target x86_64-unknown-linux-musl --path .
`
The error is long, but is clearly a linking issue.  The following is an example of an error:

error: linking with `cc` failed: exit code: 1

= note: /home/rust/src/target/x86_64-unknown-linux-musl/release/build/nlopt-ae6f811d6a4d96eb/out/lib/libnlopt.a(options.c.o): In function `nlopt_set_errmsg':
          options.c:(.text.nlopt_set_errmsg+0xc0): undefined reference to `__stack_chk_fail'
          /home/rust/src/target/x86_64-unknown-linux-musl/release/build/nlopt-ae6f811d6a4d96eb/out/lib/libnlopt.a(optimize.c.o): In function `nlopt_optimize':

**Comment by adwhit** [comment]
I think iI had a similar problem - rust issue: https://github.com/rust-lang/rust/issues/61328

**Comment by danielhstahl** [comment]
Good to know.  Its unfortunate that this is unresolved...going back to 1.31 is not an option for me.

**Comment by adwhit** [comment]
I spent a long time tinkering with build flags to get a static binary in the first place. You may be able to find some magic combination that makes them work for you. The place to look is https://github.com/adwhit/rust-nlopt/blob/c1cdd36c8444ebe9329d9d9cb7f37ee9824545c1/build.rs

**Comment by danielhstahl** [comment]
I went down this rabbit hole yesterday...manipulated the build.rs and even re-worked the cmakelists from the C++ library.  All to no avail...I was trying to use the "scratch" image (which I had at ~5 mb including binary) but I'll make due with distroless/cc-debian10, which allows me to run the GNU build at <30mb.
