### ISSUE TITLE
Upgrade to nlopt 2.7.0

### ISSUE THREAD

**Issue by relf** [adwhit/rust-nlopt#4]
Hi, thanks for your swift response to my PR #3. 
I would like to know if you have any plan to upgrade to nlopt 2.7.0?

**Comment by adwhit** [comment]
Hi. I have thought about updating to `2.7.0` but I'm not sure I'll have the time to do it myself, at least at the moment. But I would accept a pull request.

**Comment by relf** [comment]
Yeah the same here, but hopefully I'll give it a try.
